version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3006:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - "3007:3306"
    volumes:
      - mariadb_volume:/var/lib/mysql

  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgresql_volume:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: admin
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/bitnami/redis/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"      # Cổng cho AMQP (Application Messaging Protocol)
      - "15672:15672"    # Cổng cho RabbitMQ Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./deployment/config/prometheus/:/etc/prometheus/
      - ./deployment/data/prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
    volumes:
      - ./deployment/data/grafana_data:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SING_UP: 'false'
      GF_SERVER_DOMAIN: localhost
      GF_LOG_MODE: "console file"
      GF_LOG_FILTERS: "alerting.notifier.slack:debug alertmanager:debug ngalert:debug"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'


  mysql_exporter:
    image: prom/mysqld-exporter
    container_name: mysql_exporter
    ports:
      - "9104:9104"
    command:
      - '--log.level=debug'
      - '--collect.engine_innodb_status'
      - '--collect.info_schema.processlist'
      - '--collect.info_schema.tables'
      - '--collect.info_schema.query_response_time'
      - '--collect.perf_schema.file_events'
      - '--collect.perf_schema.eventsstatements'
      - '--collect.perf_schema.indexiowaits'
      - '--collect.global_status'
#      - '--ignore-tables'
      - "--mysqld.username=root:admin"
      - "--mysqld.address=172.17.0.1:3006"
    depends_on:
      - mysql

  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    environment:
      REDIS_ADDR: redis://host.docker.internal:6379
      REDIS_PASSWORD: admin
    ports:
      - "9121:9121"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

volumes:
  mysql_volume:
  mariadb_volume:
  postgresql_volume:
  redis_volume:
  mongodb_volume:
  rabbitmq_data: