global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]
    metrics_path: "/metrics"

  - job_name: springboot_application
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:8080" ]
    metrics_path: "/actuator/prometheus"

  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9100" ]

  - job_name: mysql_exporter
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9104" ]
    metrics_path: "/metrics"

  - job_name: redis_exporter
    scrape_interval: 5s
    static_configs:
        - targets: [ "host.docker.internal:9121" ]
    metrics_path: "/metrics"